language: node_js
node_js:
- '4'
- '5'
- '6'
notifications:
  slack:
    secure: j21znFB39I6WUh73jUQjYLyj748lEXcbtJqlkju5pZ96oUL/9rNr4YG/dFHYkCCZ0eKoxanoZ8Dnl3GMqI3YTOkaeWKWtI11hz+QqenVIZctAEO1Tes1aduT+DzONNK9dmwzhaYV963Wnj8vILhmV7voB83NuONuNSsEjW2eJl8ou0aVEKGsmegLdix0jPQflyZRL157TGrx0soAh53QOrnAfRkVXUpR451Byd9UOo1Pa8s/O+GkmGJKs9fkLxaTj8CR+lrY8scEw8yJsLpGajd2VvZttjPrNSk16+d6LDwHZGjqD96GQGOad2rkISwn2qPqMYOeBhnnb4FPqXsOYQZVrn1JCa1FPeE3nnC+wWntdqM1dQpUYHmeRrSy8kA+wBOrFcoFPmVxcmV61mmvickN7PKd76c8Pf6G48UhLTTK8QVBavua3uRPSUsiLUBRYzcWanbWpodFSC2BNGNgYmCbyjyLbkFqBltep58o+IfwPxJi2EmsJpFiM3pbhgio+XRODmSaLhGooW4Ahyjaw/BxF3K8df7zzeBhUXnpAB4P99xHjiSii+l1ScrYwN+PJvv/EdFTJ0byieERUDp5JbIgSxDiUJuQGwR12HyObEP1wOzE6aQAjh82T29o6bxqtLEZP2fKgEkwLN/DDk+6IJgTiVC0Stn5IbEDOMVd4Ho=
